// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NavBar: typeof import('./src/components/navBar/index.vue')['default']
    NutNavbar: typeof import('@nutui/nutui-taro')['Navbar']
    NutTabbar: typeof import('@nutui/nutui-taro')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui-taro')['TabbarItem']
    TabBar: typeof import('./src/components/tabBar/index.vue')['default']
  }
}
